name: Deploy to hosting

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Check Current Directory
        run: pwd

      - name: Check List Directory
        run: ls
      
      - name: Ensure Build Directory Exists
        run: mkdir -p build
        
      - name: Check New Created Directory
        run: ls
        
      - name: Move Build Folder Contents
        run: mv /public/build/{.,}* ./build/
        
      - name: Clear Unimportant Folders
        run: |
          if [ -d "vendor" ]; then
            rm -rf vendor
            echo "vendor folder has been removed."
          else
            echo "vendor folder does not exist. Skipping removal."
          fi
          if [ -d "node_modules" ]; then
            rm -rf node_modules
            echo "node_modules folder has been removed."
          else
            echo "node_modules folder does not exist. Skipping removal."
          fi
          if [ -d "public" ]; then
            rm -rf public
            echo "public folder has been removed."
          else
            echo "public folder does not exist. Skipping removal."
          fi
          if [ -d ".git" ]; then
            rm -rf .git
            echo ".git folder has been removed."
          else
            echo ".git folder does not exist. Skipping removal."
          fi
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with: 
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD}}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            vendor
            node_modules

          
      - name: Extract Vendor Zip (Post-Upload Step)
        run: |
          echo "Unzipping vendor folder"
          curl -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} -T extract_vendor.sh ftp://${{ secrets.FTP_SERVER }}/public_html/extract_vendor.sh
          curl -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/public_html/extract_vendor.sh
