name: Deploy to hosting

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check Current Directory
        run: pwd
      - name: Move Build Folder
        run: mv ./public/build/{.,}* ./build/
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with: 
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD}}
          local-dir: ./
          server-dir: /public_html/
